### ISSUE TITLE
[FEATURE]: Support Vitest 5.0.0

### ISSUE THREAD

**Issue by marcospereira** [LukasNiessen/ArchUnitTS#105]
# Feature Request

Support Vitest 5.0.0 release: <https://github.com/vitest-dev/vitest/releases/tag/v5.0.0>.

## Problem

Currently, updating to Vitest 5.0.0 causes' npx tsc ' to fail with the following error:

```
error TS2339: Property 'toPassAsync' does not exist on type 'Assertion<void, MetricCondition>'.

11   await expect(rule).toPassAsync();
```

Everything works perfectly with Vitest 4.1.11.

Reproducer: https://github.com/marcospereira/ArchUnitTS-Vitest-Example.

The `main` branch passes `npm run build`. The [`marcospereira/deps/vitest-5.x`](https://github.com/marcospereira/ArchUnitTS-Vitest-Example/tree/marcospereira/deps/vitest-5.x) branch fails with the error above (for multiple files).

## Proposed Solution

Not sure how to support both Vitest major versions

## Use Case

My project build will work as expected when updating Vitest to 5.0.0.

Ideally, nothing should change in existing arch-unit tests.

## 🔄 Alternatives Considered

**Describe alternatives you've considered**

## 📊 Impact Assessment

**What areas would this affect?**

- [x] Test framework integration

## 🎨 Implementation Ideas

No.

## ✋ Checklist

- [x] I have searched existing issues to make sure this isn't a duplicate
- [x] I have provided a clear use case
- [x] I have thought about backward compatibility
